import template from './templates/home.html?raw';
import {cities} from './metro';
import {getFees,feeRows} from './fees';
const base='https://phoenix.wholesaledoubleclose.click';
const style='<link rel="stylesheet" href="/styles.css"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="icon" href="/favicon.svg">';
const nav='<nav><a href="/">Home</a> · <a href="/how-double-closing-works-in-arizona/">How it works</a> · <a href="/double-close-vs-assignment/">Versus assignment</a> · <a href="/transactional-funding-fees/">Funding fees</a> · <a href="/#deal-form">Submit your deal</a></nav>';
const header=template.match(/<header class="site-header"[\s\S]*?<\/header>/)?.[0].replaceAll('href="#','href="/#').replace('href="/#top"','href="/"') ?? '';
const areas='<li class="site-nav__dropdown"><button class="site-nav__dropdown-trigger" type="button" aria-expanded="false" aria-controls="service-area-menu">Service Areas <span aria-hidden="true">⌄</span></button><div class="site-nav__dropdown-menu" id="service-area-menu"><div class="site-nav__dropdown-grid">'+cities.map(c=>'<a href="/'+c.slug+'/">'+c.name+'</a>').join('')+'</div></div></li>';
const guideHeader=header.replace('</ul>',areas+'</ul>');
export function guide(title:string,path:string,body:string){const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${title} | Phoenix Wholesale Double Close</title><meta name="description" content="${title}: a Phoenix Metro guide to wholesale double closings and transactional funding."><link rel="canonical" href="${base}${path}">${style}</head><body><a class="skip-link" href="#main">Skip to content</a>${guideHeader}<main id="main"><section class="section"><div class="container"><h1>${title}</h1>${body}</div></section></main><script src="/script.js"></script><footer class="site-footer"><div class="container">Phoenix Wholesale Double Close · ${nav}<p>Funding subject to transaction review. Ask the escrow officer about requirements for your file.</p><a href="/privacy/">Privacy</a> · <a href="/terms/">Terms</a></div></footer></body></html>`;return new Response(html,{headers:{'content-type':'text/html; charset=utf-8'}})}
export async function feesGuide(){const t=await getFees();const rows=feeRows(t).map(([l,v])=>`<tr><th scope="row">${l}</th><td>${v}</td></tr>`).join('');const fmt=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);const cap=Number(t.tier1Cap.replace(/[^0-9.]/g,''))*(t.tier1Cap.toUpperCase().includes('M')?1000000:t.tier1Cap.toUpperCase().includes('K')?1000:1), min=Number(t.tier1Minimum.replace(/[^0-9.]/g,'')),rate=Number(t.tier1Rate.replace('%',''))/100;const examples=[cap/5,cap/2].map(amount=>`<li>For a sample ${fmt(amount)} funding amount in the first tier, ${t.tier1Rate} is ${fmt(amount*rate)}; the fee would be ${fmt(Math.max(min,amount*rate))} after the ${t.tier1Minimum} minimum. This excludes closing and title costs.</li>`).join('');return guide('Transactional Funding Fees','/transactional-funding-fees/',`<p>The same published schedule applies across the Phoenix Metro service area. A written transaction review determines the actual fee and closing costs.</p><div class="fee-table-wrap"><table class="fee-table"><caption>Funding fee schedule from the shared WDC sheet</caption><thead><tr><th scope="col">Funding / condition</th><th scope="col">Fee</th></tr></thead><tbody>${rows}</tbody></table></div><h2>Worked fee examples</h2><p>These are illustrative calculations using the current sheet values, not offers.</p><ul>${examples}</ul><h2>What changes the cost</h2><p>Extra days, a second closing company, special paperwork and separate escrow costs may change the total. Confirm your actual transaction's written terms before relying on an estimate.</p><p><a href="/#deal-form">Submit your deal for review</a>.</p>`)}
